services:
  nginx:
    image: nginx:1.22.1
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - '443:443'
    networks:
      - lan
    volumes:
      - type: volume
        source: wordpress
        target: /var/www/html
        volume:
          nocopy: true
    depends_on:
      - wordpress
    restart: always

  wordpress:
    image: wordpress:6.1.1
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_ROLE: ${WP_USER_ROLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    expose:
      - "9000"
    networks:
      - lan
    volumes:
      - type: volume
        source: wordpress
        target: /var/www/html
        volume:
          nocopy: false
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:10.6.12
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
    expose:
      - "3306"
    networks:
      - lan
    volumes:
      - ${HOME}/data/DB:/var/lib/mysql
    restart: always

networks:
  lan:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      device: ${HOME}/data/WordPress
      type: none
      o: bind
